# Generated by Django 5.2.4 on 2025-07-10 12:43

import job.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_alter_job_experience_alter_job_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='image',
            field=models.ImageField(default='', upload_to=job.models.Upload),
            preserve_default=False,
        ),
    ]
